---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "ProductityTools.Homer"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "PT.Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Task3"
        logo: "assets/icons/TaskList.png"
        subtitle: ""
        tag: "pt.app"
        keywords: ""
        url: "https://task3web.z13.web.core.windows.net/"
        target: "_blank" # optional html a tag target attribute
      - name: "Journal"
        logo: "assets/icons/Jorunal.png"
        subtitle: ""
        tag: "pt.app"
        url: "https://meetingsweb.z13.web.core.windows.net/"
      - name: "Techbricks"
        logo: "assets/icons/TechBricks.png"
        subtitle: ""
        tag: "pt.app"
        url: "https://pttechbricksprod.web.app/"
      - name: "Transfers"
        logo: "assets/icons/TechBricks.png"
        subtitle: ""
        tag: "pt.app"
        url: "https://transfersweb.z16.web.core.windows.net/"
      - name: "Places"
        logo: "assets/icons/TechBricks.png"
        subtitle: ""
        tag: "pt.places"
        url: "https://ptplacesprod.web.app/"
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Prism"
        logo: "assets/icons/PhotoPrism.png"
        subtitle: ""
        tag: "app"
        keywords: "self hosted reddit"
        url: "http://photos.productivitytools.top:7010/"
        target: "_blank" # optional html a tag target attribute
      - name: "Passbolt"
        logo: "assets/icons/Passbolt.png"
        subtitle: ""
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://passbolt.productivitytools.top:443/"
        target: "_blank" # optional html a tag target attribute
  - name: "Google App Scripts"
    icon: "fas fa-cloud"
    items:
      - name: "Newsweek"
        logo: "assets/icons/Newsweek.png"
        subtitle: ""
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://script.google.com/macros/s/AKfycby78y4w07vl83rXG7QOPqH0XSIkWLntggojsoj3tljO9f0RrJ0SVEl3Y9HIy9TFJP6w/exec"
        target: "_blank" # optional html a tag target attribute
      
